//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.AnyaDodelat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График работы.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикРаботы CustomAttributes)

    // *** End programmer edit section *** (ГрафикРаботы CustomAttributes)
    [AutoAltered()]
    [Caption("График работы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикРаботыE", new string[] {
            "числоЧасов as \'Число часов\'",
            "времяНачала as \'Время начала\'",
            "времяКонца as \'Время конца\'",
            "типЗанятости as \'Тип занятости\'",
            "сотрудник as \'Сотрудник\'",
            "сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ГрафикРаботыE", "сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ГрафикРаботыL", new string[] {
            "числоЧасов as \'Число часов\'",
            "времяНачала as \'Время начала\'",
            "времяКонца as \'Время конца\'",
            "типЗанятости as \'Тип занятости\'",
            "сотрудник.ФИО as \'ФИО\'"})]
    public class ГрафикРаботы : ICSSoft.STORMNET.DataObject
    {
        
        private double fчислоЧасов;
        
        private System.DateTime fвремяНачала;
        
        private System.DateTime fвремяКонца;
        
        private IIS.AnyaDodelat.ТипЗанятости fтипЗанятости;
        
        private IIS.AnyaDodelat.сотрудник fсотрудник;
        
        // *** Start programmer edit section *** (ГрафикРаботы CustomMembers)

        // *** End programmer edit section *** (ГрафикРаботы CustomMembers)

        
        /// <summary>
        /// времяКонца.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.времяКонца CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.времяКонца CustomAttributes)
        public virtual System.DateTime времяКонца
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.времяКонца Get start)

                // *** End programmer edit section *** (ГрафикРаботы.времяКонца Get start)
                System.DateTime result = this.fвремяКонца;
                // *** Start programmer edit section *** (ГрафикРаботы.времяКонца Get end)

                // *** End programmer edit section *** (ГрафикРаботы.времяКонца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.времяКонца Set start)

                // *** End programmer edit section *** (ГрафикРаботы.времяКонца Set start)
                this.fвремяКонца = value;
                // *** Start programmer edit section *** (ГрафикРаботы.времяКонца Set end)

                // *** End programmer edit section *** (ГрафикРаботы.времяКонца Set end)
            }
        }
        
        /// <summary>
        /// времяНачала.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.времяНачала CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.времяНачала CustomAttributes)
        public virtual System.DateTime времяНачала
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.времяНачала Get start)

                // *** End programmer edit section *** (ГрафикРаботы.времяНачала Get start)
                System.DateTime result = this.fвремяНачала;
                // *** Start programmer edit section *** (ГрафикРаботы.времяНачала Get end)

                // *** End programmer edit section *** (ГрафикРаботы.времяНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.времяНачала Set start)

                // *** End programmer edit section *** (ГрафикРаботы.времяНачала Set start)
                this.fвремяНачала = value;
                // *** Start programmer edit section *** (ГрафикРаботы.времяНачала Set end)

                // *** End programmer edit section *** (ГрафикРаботы.времяНачала Set end)
            }
        }
        
        /// <summary>
        /// типЗанятости.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.типЗанятости CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.типЗанятости CustomAttributes)
        public virtual IIS.AnyaDodelat.ТипЗанятости типЗанятости
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.типЗанятости Get start)

                // *** End programmer edit section *** (ГрафикРаботы.типЗанятости Get start)
                IIS.AnyaDodelat.ТипЗанятости result = this.fтипЗанятости;
                // *** Start programmer edit section *** (ГрафикРаботы.типЗанятости Get end)

                // *** End programmer edit section *** (ГрафикРаботы.типЗанятости Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.типЗанятости Set start)

                // *** End programmer edit section *** (ГрафикРаботы.типЗанятости Set start)
                this.fтипЗанятости = value;
                // *** Start programmer edit section *** (ГрафикРаботы.типЗанятости Set end)

                // *** End programmer edit section *** (ГрафикРаботы.типЗанятости Set end)
            }
        }
        
        /// <summary>
        /// числоЧасов.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.числоЧасов CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.числоЧасов CustomAttributes)
        public virtual double числоЧасов
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.числоЧасов Get start)

                // *** End programmer edit section *** (ГрафикРаботы.числоЧасов Get start)
                double result = this.fчислоЧасов;
                // *** Start programmer edit section *** (ГрафикРаботы.числоЧасов Get end)

                // *** End programmer edit section *** (ГрафикРаботы.числоЧасов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.числоЧасов Set start)

                // *** End programmer edit section *** (ГрафикРаботы.числоЧасов Set start)
                this.fчислоЧасов = value;
                // *** Start programmer edit section *** (ГрафикРаботы.числоЧасов Set end)

                // *** End programmer edit section *** (ГрафикРаботы.числоЧасов Set end)
            }
        }
        
        /// <summary>
        /// График работы.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.сотрудник CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "сотрудник"})]
        [NotNull()]
        public virtual IIS.AnyaDodelat.сотрудник сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.сотрудник Get start)

                // *** End programmer edit section *** (ГрафикРаботы.сотрудник Get start)
                IIS.AnyaDodelat.сотрудник result = this.fсотрудник;
                // *** Start programmer edit section *** (ГрафикРаботы.сотрудник Get end)

                // *** End programmer edit section *** (ГрафикРаботы.сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.сотрудник Set start)

                // *** End programmer edit section *** (ГрафикРаботы.сотрудник Set start)
                this.fсотрудник = value;
                // *** Start programmer edit section *** (ГрафикРаботы.сотрудник Set end)

                // *** End programmer edit section *** (ГрафикРаботы.сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикРаботыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикРаботыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикРаботыE", typeof(IIS.AnyaDodelat.ГрафикРаботы));
                }
            }
            
            /// <summary>
            /// "ГрафикРаботыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикРаботыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикРаботыL", typeof(IIS.AnyaDodelat.ГрафикРаботы));
                }
            }
        }
    }
}
