//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.AnyaDodelat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отсутствие.
    /// </summary>
    // *** Start programmer edit section *** (Отсутствие CustomAttributes)

    // *** End programmer edit section *** (Отсутствие CustomAttributes)
    [AutoAltered()]
    [Caption("Отсутствие сотрудника")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтсутствиеE", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаКонца as \'Дата конца\'",
            "Причина as \'Причина\'",
            "Комментарий as \'Комментарий\'",
            "сотрудник as \'Сотрудник\'",
            "сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ОтсутствиеE", "сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтсутствиеL", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаКонца as \'Дата конца\'",
            "Причина as \'Причина\'",
            "Комментарий as \'Комментарий\'",
            "сотрудник.ФИО as \'ФИО\'"})]
    public class Отсутствие : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаКонца;
        
        private IIS.AnyaDodelat.ТипЗанятости fПричина;
        
        private string fКомментарий;
        
        private IIS.AnyaDodelat.сотрудник fсотрудник;
        
        // *** Start programmer edit section *** (Отсутствие CustomMembers)

        // *** End programmer edit section *** (Отсутствие CustomMembers)

        
        /// <summary>
        /// ДатаКонца.
        /// </summary>
        // *** Start programmer edit section *** (Отсутствие.ДатаКонца CustomAttributes)

        // *** End programmer edit section *** (Отсутствие.ДатаКонца CustomAttributes)
        public virtual System.DateTime ДатаКонца
        {
            get
            {
                // *** Start programmer edit section *** (Отсутствие.ДатаКонца Get start)

                // *** End programmer edit section *** (Отсутствие.ДатаКонца Get start)
                System.DateTime result = this.fДатаКонца;
                // *** Start programmer edit section *** (Отсутствие.ДатаКонца Get end)

                // *** End programmer edit section *** (Отсутствие.ДатаКонца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отсутствие.ДатаКонца Set start)

                // *** End programmer edit section *** (Отсутствие.ДатаКонца Set start)
                this.fДатаКонца = value;
                // *** Start programmer edit section *** (Отсутствие.ДатаКонца Set end)

                // *** End programmer edit section *** (Отсутствие.ДатаКонца Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (Отсутствие.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (Отсутствие.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (Отсутствие.ДатаНачала Get start)

                // *** End programmer edit section *** (Отсутствие.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (Отсутствие.ДатаНачала Get end)

                // *** End programmer edit section *** (Отсутствие.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отсутствие.ДатаНачала Set start)

                // *** End programmer edit section *** (Отсутствие.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (Отсутствие.ДатаНачала Set end)

                // *** End programmer edit section *** (Отсутствие.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Отсутствие.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Отсутствие.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Отсутствие.Комментарий Get start)

                // *** End programmer edit section *** (Отсутствие.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Отсутствие.Комментарий Get end)

                // *** End programmer edit section *** (Отсутствие.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отсутствие.Комментарий Set start)

                // *** End programmer edit section *** (Отсутствие.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Отсутствие.Комментарий Set end)

                // *** End programmer edit section *** (Отсутствие.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Причина.
        /// </summary>
        // *** Start programmer edit section *** (Отсутствие.Причина CustomAttributes)

        // *** End programmer edit section *** (Отсутствие.Причина CustomAttributes)
        public virtual IIS.AnyaDodelat.ТипЗанятости Причина
        {
            get
            {
                // *** Start programmer edit section *** (Отсутствие.Причина Get start)

                // *** End programmer edit section *** (Отсутствие.Причина Get start)
                IIS.AnyaDodelat.ТипЗанятости result = this.fПричина;
                // *** Start programmer edit section *** (Отсутствие.Причина Get end)

                // *** End programmer edit section *** (Отсутствие.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отсутствие.Причина Set start)

                // *** End programmer edit section *** (Отсутствие.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (Отсутствие.Причина Set end)

                // *** End programmer edit section *** (Отсутствие.Причина Set end)
            }
        }
        
        /// <summary>
        /// Отсутствие.
        /// </summary>
        // *** Start programmer edit section *** (Отсутствие.сотрудник CustomAttributes)

        // *** End programmer edit section *** (Отсутствие.сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "сотрудник"})]
        [NotNull()]
        public virtual IIS.AnyaDodelat.сотрудник сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Отсутствие.сотрудник Get start)

                // *** End programmer edit section *** (Отсутствие.сотрудник Get start)
                IIS.AnyaDodelat.сотрудник result = this.fсотрудник;
                // *** Start programmer edit section *** (Отсутствие.сотрудник Get end)

                // *** End programmer edit section *** (Отсутствие.сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отсутствие.сотрудник Set start)

                // *** End programmer edit section *** (Отсутствие.сотрудник Set start)
                this.fсотрудник = value;
                // *** Start programmer edit section *** (Отсутствие.сотрудник Set end)

                // *** End programmer edit section *** (Отсутствие.сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтсутствиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтсутствиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтсутствиеE", typeof(IIS.AnyaDodelat.Отсутствие));
                }
            }
            
            /// <summary>
            /// "ОтсутствиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтсутствиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтсутствиеL", typeof(IIS.AnyaDodelat.Отсутствие));
                }
            }
        }
    }
}
